!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.3 (r3163) - 09/25/2009 09:03
!
!  Differentiation of scalar_triple_product in reverse (adjoint) mode:
!   gradient, with respect to input variables: a b c
!   of linear combination of output variables: scalar_triple_product
SUBROUTINE SCALAR_TRIPLE_PRODUCT_B(a, ab, b, bb, c, cb, &
&  scalar_triple_productb)
  IMPLICIT NONE
  DOUBLE PRECISION :: a(3), b(3), c(3), scalar_triple_product
  DOUBLE PRECISION :: ab(3), bb(3), cb(3), scalar_triple_productb
  DOUBLE PRECISION, DIMENSION(3) :: tmp
  DOUBLE PRECISION, DIMENSION(3) :: tmp0
  DOUBLE PRECISION, DIMENSION(3) :: tmp1
  DOUBLE PRECISION :: temp3
  DOUBLE PRECISION :: temp2
  DOUBLE PRECISION :: temp1
  DOUBLE PRECISION :: temp0
  DOUBLE PRECISION :: tmpb(3)
  DOUBLE PRECISION :: tmp0b(3)
  DOUBLE PRECISION :: temp3b
  DOUBLE PRECISION :: tempb
  DOUBLE PRECISION :: temp1b
  INTRINSIC SQRT
  DOUBLE PRECISION :: temp
  DOUBLE PRECISION :: tmp1b(3)
  DOUBLE PRECISION :: temp4
! Compute the scalar triple product of a*(b x c)
! This is the determinate of:
!                   [a1 a2 a3] [a b c]
!(b x c) * a  = det [b1 b2 b3] [d e f]
!                   [c1 c2 c3] [g h i]
!                         aei          +        bfg     +        cdh     −     afh       −     bdi       − ceg.
  tmp = a/SQRT(a(1)*a(1)+a(2)*a(2)+a(3)*a(3))
  CALL PUSHREAL8ARRAY(a, 3)
  a = tmp
  tmp0 = b/SQRT(b(1)*b(1)+b(2)*b(2)+b(3)*b(3))
  CALL PUSHREAL8ARRAY(b, 3)
  b = tmp0
  tmp1 = c/SQRT(c(1)*c(1)+c(2)*c(2)+c(3)*c(3))
  CALL PUSHREAL8ARRAY(c, 3)
  c = tmp1
  ab = 0.D0
  bb = 0.D0
  cb = 0.D0
  ab(1) = (c(3)*b(2)-c(2)*b(3))*scalar_triple_productb
  bb(2) = (c(3)*a(1)-c(1)*a(3))*scalar_triple_productb
  cb(3) = (a(1)*b(2)-a(2)*b(1))*scalar_triple_productb
  ab(2) = (c(1)*b(3)-c(3)*b(1))*scalar_triple_productb
  bb(3) = (c(1)*a(2)-c(2)*a(1))*scalar_triple_productb
  cb(1) = (a(2)*b(3)-a(3)*b(2))*scalar_triple_productb
  ab(3) = (c(2)*b(1)-c(1)*b(2))*scalar_triple_productb
  bb(1) = (c(2)*a(3)-c(3)*a(2))*scalar_triple_productb
  cb(2) = (a(3)*b(1)-a(1)*b(3))*scalar_triple_productb
  CALL POPREAL8ARRAY(c, 3)
  tmp1b = cb
  temp3 = c(1)**2 + c(2)**2 + c(3)**2
  temp4 = SQRT(temp3)
  cb = tmp1b/temp4
  IF (temp3 .EQ. 0.0) THEN
    temp3b = 0.0
  ELSE
    temp3b = SUM(-(c*tmp1b/temp4**2))/(2.0*temp4)
  END IF
  cb(1) = cb(1) + 2*c(1)*temp3b
  cb(2) = cb(2) + 2*c(2)*temp3b
  cb(3) = cb(3) + 2*c(3)*temp3b
  CALL POPREAL8ARRAY(b, 3)
  tmp0b = bb
  temp1 = b(1)**2 + b(2)**2 + b(3)**2
  temp2 = SQRT(temp1)
  bb = tmp0b/temp2
  IF (temp1 .EQ. 0.0) THEN
    temp1b = 0.0
  ELSE
    temp1b = SUM(-(b*tmp0b/temp2**2))/(2.0*temp2)
  END IF
  bb(1) = bb(1) + 2*b(1)*temp1b
  bb(2) = bb(2) + 2*b(2)*temp1b
  bb(3) = bb(3) + 2*b(3)*temp1b
  CALL POPREAL8ARRAY(a, 3)
  tmpb = ab
  temp = a(1)**2 + a(2)**2 + a(3)**2
  temp0 = SQRT(temp)
  ab = tmpb/temp0
  IF (temp .EQ. 0.0) THEN
    tempb = 0.0
  ELSE
    tempb = SUM(-(a*tmpb/temp0**2))/(2.0*temp0)
  END IF
  ab(1) = ab(1) + 2*a(1)*tempb
  ab(2) = ab(2) + 2*a(2)*tempb
  ab(3) = ab(3) + 2*a(3)*tempb
END SUBROUTINE SCALAR_TRIPLE_PRODUCT_B
