!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3375) - 10 Feb 2010 15:08
!
!  Differentiation of skew_hexa in reverse (adjoint) mode:
!   gradient     of useful results: skew
!   with respect to varying inputs: points skew
!   RW status of diff variables: points:out skew:in-zero
SUBROUTINE SKEW_HEXA_B(points, pointsb, skew, skewb)
  IMPLICIT NONE
  DOUBLE PRECISION :: points(8, 3), skew
  DOUBLE PRECISION :: pointsb(8, 3), skewb
  DOUBLE PRECISION :: SCALAR_TRIPLE_PRODUCT
  DOUBLE PRECISION, DIMENSION(3) :: arg1
  DOUBLE PRECISION, DIMENSION(3) :: arg1b
  DOUBLE PRECISION, DIMENSION(3) :: arg2
  DOUBLE PRECISION, DIMENSION(3) :: arg2b
  DOUBLE PRECISION, DIMENSION(3) :: arg3
  DOUBLE PRECISION, DIMENSION(3) :: arg3b
  DOUBLE PRECISION :: result1
  DOUBLE PRECISION :: result1b
  skew = 1.0
  arg1(:) = points(2, :) - points(1, :)
  arg2(:) = points(3, :) - points(1, :)
  arg3(:) = points(5, :) - points(1, :)
  CALL PUSHREAL8ARRAY(arg3, 3)
  CALL PUSHREAL8ARRAY(arg2, 3)
  CALL PUSHREAL8ARRAY(arg1, 3)
  result1 = SCALAR_TRIPLE_PRODUCT(arg1(:), arg2(:), arg3(:))
  CALL PUSHREAL8(skew)
  skew = skew*result1
  arg1(:) = points(4, :) - points(2, :)
  arg2(:) = points(1, :) - points(2, :)
  arg3(:) = points(6, :) - points(2, :)
  CALL PUSHREAL8ARRAY(arg3, 3)
  CALL PUSHREAL8ARRAY(arg2, 3)
  CALL PUSHREAL8ARRAY(arg1, 3)
  result1 = SCALAR_TRIPLE_PRODUCT(arg1(:), arg2(:), arg3(:))
  CALL PUSHREAL8(skew)
  skew = skew*result1
  arg1(:) = points(1, :) - points(3, :)
  arg2(:) = points(4, :) - points(3, :)
  arg3(:) = points(7, :) - points(3, :)
  CALL PUSHREAL8(result1)
  CALL PUSHREAL8ARRAY(arg3, 3)
  CALL PUSHREAL8ARRAY(arg2, 3)
  CALL PUSHREAL8ARRAY(arg1, 3)
  result1 = SCALAR_TRIPLE_PRODUCT(arg1(:), arg2(:), arg3(:))
  CALL PUSHREAL8(skew)
  skew = skew*result1
  arg1(:) = points(3, :) - points(4, :)
  arg2(:) = points(2, :) - points(4, :)
  arg3(:) = points(8, :) - points(4, :)
  CALL PUSHREAL8(result1)
  CALL PUSHREAL8ARRAY(arg3, 3)
  CALL PUSHREAL8ARRAY(arg2, 3)
  CALL PUSHREAL8ARRAY(arg1, 3)
  result1 = SCALAR_TRIPLE_PRODUCT(arg1(:), arg2(:), arg3(:))
  CALL PUSHREAL8(skew)
  skew = skew*result1
  arg1(:) = points(7, :) - points(5, :)
  arg2(:) = points(6, :) - points(5, :)
  arg3(:) = points(1, :) - points(5, :)
  CALL PUSHREAL8(result1)
  CALL PUSHREAL8ARRAY(arg3, 3)
  CALL PUSHREAL8ARRAY(arg2, 3)
  CALL PUSHREAL8ARRAY(arg1, 3)
  result1 = SCALAR_TRIPLE_PRODUCT(arg1(:), arg2(:), arg3(:))
  CALL PUSHREAL8(skew)
  skew = skew*result1
  arg1(:) = points(5, :) - points(6, :)
  arg2(:) = points(8, :) - points(6, :)
  arg3(:) = points(2, :) - points(6, :)
  CALL PUSHREAL8(result1)
  CALL PUSHREAL8ARRAY(arg3, 3)
  CALL PUSHREAL8ARRAY(arg2, 3)
  CALL PUSHREAL8ARRAY(arg1, 3)
  result1 = SCALAR_TRIPLE_PRODUCT(arg1(:), arg2(:), arg3(:))
  CALL PUSHREAL8(skew)
  skew = skew*result1
  arg1(:) = points(8, :) - points(7, :)
  arg2(:) = points(5, :) - points(7, :)
  arg3(:) = points(3, :) - points(7, :)
  CALL PUSHREAL8(result1)
  CALL PUSHREAL8ARRAY(arg3, 3)
  CALL PUSHREAL8ARRAY(arg2, 3)
  CALL PUSHREAL8ARRAY(arg1, 3)
  result1 = SCALAR_TRIPLE_PRODUCT(arg1(:), arg2(:), arg3(:))
  CALL PUSHREAL8(skew)
  skew = skew*result1
  arg1(:) = points(6, :) - points(8, :)
  arg2(:) = points(7, :) - points(8, :)
  arg3(:) = points(4, :) - points(8, :)
  CALL PUSHREAL8(result1)
  CALL PUSHREAL8ARRAY(arg3, 3)
  CALL PUSHREAL8ARRAY(arg2, 3)
  CALL PUSHREAL8ARRAY(arg1, 3)
  result1 = SCALAR_TRIPLE_PRODUCT(arg1(:), arg2(:), arg3(:))
  result1b = skew*skewb
  skewb = result1*skewb
  CALL POPREAL8ARRAY(arg1, 3)
  CALL POPREAL8ARRAY(arg2, 3)
  CALL POPREAL8ARRAY(arg3, 3)
  CALL POPREAL8(result1)
  CALL SCALAR_TRIPLE_PRODUCT_B(arg1(:), arg1b(:), arg2(:), arg2b(:), &
&                         arg3(:), arg3b(:), result1b)
  pointsb = 0.D0
  pointsb(4, :) = arg3b(:)
  pointsb(8, :) = -arg3b(:)
  pointsb(7, :) = pointsb(7, :) + arg2b(:)
  pointsb(8, :) = pointsb(8, :) - arg2b(:)
  pointsb(6, :) = pointsb(6, :) + arg1b(:)
  pointsb(8, :) = pointsb(8, :) - arg1b(:)
  CALL POPREAL8(skew)
  result1b = skew*skewb
  skewb = result1*skewb
  CALL POPREAL8ARRAY(arg1, 3)
  CALL POPREAL8ARRAY(arg2, 3)
  CALL POPREAL8ARRAY(arg3, 3)
  CALL POPREAL8(result1)
  CALL SCALAR_TRIPLE_PRODUCT_B(arg1(:), arg1b(:), arg2(:), arg2b(:), &
&                         arg3(:), arg3b(:), result1b)
  pointsb(3, :) = pointsb(3, :) + arg3b(:)
  pointsb(7, :) = pointsb(7, :) - arg3b(:)
  pointsb(5, :) = pointsb(5, :) + arg2b(:)
  pointsb(7, :) = pointsb(7, :) - arg2b(:)
  pointsb(8, :) = pointsb(8, :) + arg1b(:)
  pointsb(7, :) = pointsb(7, :) - arg1b(:)
  CALL POPREAL8(skew)
  result1b = skew*skewb
  skewb = result1*skewb
  CALL POPREAL8ARRAY(arg1, 3)
  CALL POPREAL8ARRAY(arg2, 3)
  CALL POPREAL8ARRAY(arg3, 3)
  CALL POPREAL8(result1)
  CALL SCALAR_TRIPLE_PRODUCT_B(arg1(:), arg1b(:), arg2(:), arg2b(:), &
&                         arg3(:), arg3b(:), result1b)
  pointsb(2, :) = pointsb(2, :) + arg3b(:)
  pointsb(6, :) = pointsb(6, :) - arg3b(:)
  pointsb(8, :) = pointsb(8, :) + arg2b(:)
  pointsb(6, :) = pointsb(6, :) - arg2b(:)
  pointsb(5, :) = pointsb(5, :) + arg1b(:)
  pointsb(6, :) = pointsb(6, :) - arg1b(:)
  CALL POPREAL8(skew)
  result1b = skew*skewb
  skewb = result1*skewb
  CALL POPREAL8ARRAY(arg1, 3)
  CALL POPREAL8ARRAY(arg2, 3)
  CALL POPREAL8ARRAY(arg3, 3)
  CALL POPREAL8(result1)
  CALL SCALAR_TRIPLE_PRODUCT_B(arg1(:), arg1b(:), arg2(:), arg2b(:), &
&                         arg3(:), arg3b(:), result1b)
  pointsb(1, :) = pointsb(1, :) + arg3b(:)
  pointsb(5, :) = pointsb(5, :) - arg3b(:)
  pointsb(6, :) = pointsb(6, :) + arg2b(:)
  pointsb(5, :) = pointsb(5, :) - arg2b(:)
  pointsb(7, :) = pointsb(7, :) + arg1b(:)
  pointsb(5, :) = pointsb(5, :) - arg1b(:)
  CALL POPREAL8(skew)
  result1b = skew*skewb
  skewb = result1*skewb
  CALL POPREAL8ARRAY(arg1, 3)
  CALL POPREAL8ARRAY(arg2, 3)
  CALL POPREAL8ARRAY(arg3, 3)
  CALL POPREAL8(result1)
  CALL SCALAR_TRIPLE_PRODUCT_B(arg1(:), arg1b(:), arg2(:), arg2b(:), &
&                         arg3(:), arg3b(:), result1b)
  pointsb(8, :) = pointsb(8, :) + arg3b(:)
  pointsb(4, :) = pointsb(4, :) - arg3b(:)
  pointsb(2, :) = pointsb(2, :) + arg2b(:)
  pointsb(4, :) = pointsb(4, :) - arg2b(:)
  pointsb(3, :) = pointsb(3, :) + arg1b(:)
  pointsb(4, :) = pointsb(4, :) - arg1b(:)
  CALL POPREAL8(skew)
  result1b = skew*skewb
  skewb = result1*skewb
  CALL POPREAL8ARRAY(arg1, 3)
  CALL POPREAL8ARRAY(arg2, 3)
  CALL POPREAL8ARRAY(arg3, 3)
  CALL POPREAL8(result1)
  CALL SCALAR_TRIPLE_PRODUCT_B(arg1(:), arg1b(:), arg2(:), arg2b(:), &
&                         arg3(:), arg3b(:), result1b)
  pointsb(7, :) = pointsb(7, :) + arg3b(:)
  pointsb(3, :) = pointsb(3, :) - arg3b(:)
  pointsb(4, :) = pointsb(4, :) + arg2b(:)
  pointsb(3, :) = pointsb(3, :) - arg2b(:)
  pointsb(1, :) = pointsb(1, :) + arg1b(:)
  pointsb(3, :) = pointsb(3, :) - arg1b(:)
  CALL POPREAL8(skew)
  result1b = skew*skewb
  skewb = result1*skewb
  CALL POPREAL8ARRAY(arg1, 3)
  CALL POPREAL8ARRAY(arg2, 3)
  CALL POPREAL8ARRAY(arg3, 3)
  CALL SCALAR_TRIPLE_PRODUCT_B(arg1(:), arg1b(:), arg2(:), arg2b(:), &
&                         arg3(:), arg3b(:), result1b)
  pointsb(6, :) = pointsb(6, :) + arg3b(:)
  pointsb(2, :) = pointsb(2, :) - arg3b(:)
  pointsb(1, :) = pointsb(1, :) + arg2b(:)
  pointsb(2, :) = pointsb(2, :) - arg2b(:)
  pointsb(4, :) = pointsb(4, :) + arg1b(:)
  pointsb(2, :) = pointsb(2, :) - arg1b(:)
  CALL POPREAL8(skew)
  result1b = skew*skewb
  CALL POPREAL8ARRAY(arg1, 3)
  CALL POPREAL8ARRAY(arg2, 3)
  CALL POPREAL8ARRAY(arg3, 3)
  CALL SCALAR_TRIPLE_PRODUCT_B(arg1(:), arg1b(:), arg2(:), arg2b(:), &
&                         arg3(:), arg3b(:), result1b)
  pointsb(5, :) = pointsb(5, :) + arg3b(:)
  pointsb(1, :) = pointsb(1, :) - arg3b(:)
  pointsb(3, :) = pointsb(3, :) + arg2b(:)
  pointsb(1, :) = pointsb(1, :) - arg2b(:)
  pointsb(2, :) = pointsb(2, :) + arg1b(:)
  pointsb(1, :) = pointsb(1, :) - arg1b(:)
  skewb = 0.D0
END SUBROUTINE SKEW_HEXA_B
